export const ENV = {
  NODE_ENV: process.env.NODE_ENV || "dev",
  AWS_REGION: process.env.AWS_REGION || "us-east-1",
  PUBLIC_SITE_URL: process.env.PUBLIC_SITE_URL || "",
  COGNITO_USER_POOL_ID: process.env.COGNITO_USER_POOL_ID,
  COGNITO_CLIENT_ID: process.env.COGNITO_CLIENT_ID,
  USERS_TABLE: process.env.USERS_TABLE,
  BENEFITS_TABLE: process.env.BENEFITS_TABLE,
  NOTIFICATIONS_TABLE: process.env.NOTIFICATIONS_TABLE,
  DEVICES_TABLE: process.env.DEVICES_TABLE,
  AGENDA_SLOTS_TABLE: process.env.AGENDA_SLOTS_TABLE,
  APPOINTMENTS_TABLE: process.env.APPOINTMENTS_TABLE,
  AGENDA_IMPORTS_TABLE: process.env.AGENDA_IMPORTS_TABLE,
  AGENDA_BUCKET_NAME: process.env.AGENDA_BUCKET_NAME,
  APPOINTMENTS_NOTIFICATION_EMAIL: process.env.APPOINTMENTS_NOTIFICATION_EMAIL || "",
  NOTIFICATIONS_EMAIL_SOURCE: process.env.NOTIFICATIONS_EMAIL_SOURCE || "",
  APPOINTMENTS_API_BASE_URL: process.env.APPOINTMENTS_API_BASE_URL || "",
  SOFTWARE_MEDICO_BASE_URL:
    process.env.SOFTWARE_MEDICO_BASE_URL ||
    "https://clinicaisis.softwaremedico.com.co/api/v1/",
  SOFTWARE_MEDICO_USERNAME: process.env.SOFTWARE_MEDICO_USERNAME || "",
  SOFTWARE_MEDICO_PASSWORD: process.env.SOFTWARE_MEDICO_PASSWORD || "",
  SOFTWARE_MEDICO_TIMEOUT_MS: Number(process.env.SOFTWARE_MEDICO_TIMEOUT_MS || "10000"),
  SOFTWARE_MEDICO_TOKEN_TTL_SECONDS: Number(
    process.env.SOFTWARE_MEDICO_TOKEN_TTL_SECONDS || "3000"
  ),
  SOFTWARE_MEDICO_CITA_TIPO_ID: process.env.SOFTWARE_MEDICO_CITA_TIPO_ID || "",
  SOFTWARE_MEDICO_SEDE_ID: process.env.SOFTWARE_MEDICO_SEDE_ID || "",
  DEFAULT_SLOT_MINUTES: Number(process.env.DEFAULT_SLOT_MINUTES || "30"),
  DEFAULT_APPOINTMENT_COST: Number(process.env.DEFAULT_APPOINTMENT_COST || "2000"),
  DEFAULT_APPOINTMENT_CURRENCY: process.env.DEFAULT_APPOINTMENT_CURRENCY || "COP",
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID || "",
  FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL || "",
  FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY || "",
  FCM_DEFAULT_TOPIC: process.env.FCM_DEFAULT_TOPIC || "all_users",
  CONTENTFUL_SPACE_ID: process.env.CONTENTFUL_SPACE_ID,
  CONTENTFUL_ENVIRONMENT: process.env.CONTENTFUL_ENVIRONMENT || "master",
  CONTENTFUL_ACCESS_TOKEN: process.env.CONTENTFUL_ACCESS_TOKEN,
  CONTENTFUL_BLOG_CONTENT_TYPE: process.env.CONTENTFUL_BLOG_CONTENT_TYPE || "blogPost",
  SNS_PLATFORM_APPLICATION_ARN: process.env.SNS_PLATFORM_APPLICATION_ARN,
  LOG_LEVEL: process.env.LOG_LEVEL || "info",
  CORS_ALLOWED_ORIGINS: process.env.CORS_ALLOWED_ORIGINS || "*"
};

export const STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE"
};

export const NOTIFICATION_TYPES = {
  BENEFIT_ASSIGNED: "BENEFIT_ASSIGNED",
  APPOINTMENT_PREBOOKED: "agenda",
  APPOINTMENT_CONFIRMED: "agenda",
  APPOINTMENT_REJECTED: "agenda"
};

export const APPOINTMENT_STATUSES = {
  PREBOOKED: "prebooked",
  BOOKED: "booked",
  CANCELLED: "cancelled",
  REJECTED: "rejected"
};
