export const ENV = {
  NODE_ENV: process.env.NODE_ENV || "dev",
  AWS_REGION: process.env.AWS_REGION || "us-east-1",
  COGNITO_USER_POOL_ID: process.env.COGNITO_USER_POOL_ID,
  COGNITO_CLIENT_ID: process.env.COGNITO_CLIENT_ID,
  USERS_TABLE: process.env.USERS_TABLE,
  BENEFITS_TABLE: process.env.BENEFITS_TABLE,
  NOTIFICATIONS_TABLE: process.env.NOTIFICATIONS_TABLE,
  DEVICES_TABLE: process.env.DEVICES_TABLE,
  CONTENTFUL_SPACE_ID: process.env.CONTENTFUL_SPACE_ID,
  CONTENTFUL_ENVIRONMENT: process.env.CONTENTFUL_ENVIRONMENT || "master",
  CONTENTFUL_ACCESS_TOKEN: process.env.CONTENTFUL_ACCESS_TOKEN,
  CONTENTFUL_BLOG_CONTENT_TYPE: process.env.CONTENTFUL_BLOG_CONTENT_TYPE || "blogPost",
  SNS_PLATFORM_APPLICATION_ARN: process.env.SNS_PLATFORM_APPLICATION_ARN,
  LOG_LEVEL: process.env.LOG_LEVEL || "info",
  CORS_ALLOWED_ORIGINS: process.env.CORS_ALLOWED_ORIGINS || "*"
};

export const STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE"
};

export const NOTIFICATION_TYPES = {
  BENEFIT_ASSIGNED: "BENEFIT_ASSIGNED"
};
