export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_NOT_CONFIRMED: "USER_NOT_CONFIRMED",
  AUTH_PROVIDER_ERROR: "AUTH_PROVIDER_ERROR",
  INVALID_CODE: "INVALID_CODE",
  EXPIRED_CODE: "EXPIRED_CODE",
  PASSWORD_POLICY_ERROR: "PASSWORD_POLICY_ERROR",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  USER_INACTIVE: "USER_INACTIVE",
  BLOG_NOT_FOUND: "BLOG_NOT_FOUND",
  CONTENTFUL_PROVIDER_ERROR: "CONTENTFUL_PROVIDER_ERROR",
  BENEFIT_NOT_FOUND: "BENEFIT_NOT_FOUND",
  BENEFIT_NOT_ASSIGNED_TO_USER: "BENEFIT_NOT_ASSIGNED_TO_USER",
  BENEFIT_ALREADY_ASSIGNED: "BENEFIT_ALREADY_ASSIGNED",
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  DEVICE_REGISTRATION_ERROR: "DEVICE_REGISTRATION_ERROR",
  PUSH_NOTIFICATION_ERROR: "PUSH_NOTIFICATION_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
};

export class AppError extends Error {
  constructor(code, message, statusCode = 400, details = null) {
    super(message);
    this.name = "AppError";
    this.code = code;
    this.statusCode = statusCode;
    this.details = details;
  }
}

export const toHttpError = (error) => {
  if (error instanceof AppError) return error;
  return new AppError(
    ERROR_CODES.INTERNAL_SERVER_ERROR,
    "Ocurrió un error inesperado.",
    500
  );
};
